### ISSUE TITLE
gravity forms console errors

### ISSUE THREAD

**Issue by mrxkon** [wpgreece/wpgreece-theme#14]
Απλά το βάζω εδώ για να το κοιτάξω later on.

![vivaldi_2018-06-19_20-56-14](https://user-images.githubusercontent.com/22611066/41615644-7e0468ee-7404-11e8-87c8-a77656eeb443.png)

Με την πρώτη είσοδο στην σελίδα υπάρχει αυτό το error, αλλά όταν γίνει refresh ( κοινώς υπάρχει cache δεν το ξαναδείχνει ). Έτσι απλά γιατί μου σπάνε τα νεύρα τα console errors πρέπει να το κοιτάξω χαχαχα 😈

**Comment by kosvrouvas** [comment]
βλέπω δεν υπάρχει πλέον το, cloooosing!
