### ISSUE TITLE
Αλλαγή banner στην αρχική σελίδα

### ISSUE THREAD

**Issue by vbaimas** [wpgreece/wpgreece-theme#15]
Το banner αναφέρει ότι "είμαστε 3500 μέλη και συνεχίζουμε" ναι μεν δεν είναι ψέμα αλλά θα έλεγα αν μπορεί κάποιος να ενημερώσει το νούμερο (~6100) με ένα νέο μπάνερ ή να μπει κάτι ίσως ότι είμαστε χιλιάδες μέλη και να μην χρειάζεται αλλαγή συνέχεια. 

(cc George Bikas / Slack Channel https://wpgreece.slack.com/archives/C1ECH1UKG/p1528713655000042]

**Comment by kosvrouvas** [comment]
@ifrountas μπορούμε να έχουμε το banner από Πόπη να το αλλάζουμε χωρίς να ενοχλούμε;

**Comment by vagelisp** [comment]
Καλησπέρα, το είδα και είπα να βοηθήσω. Δε ξέρω αν έχετε κάνει το νέο ή όχι οπότε ανεβάζω ένα εδώ.
![greek-banner-10-2019](https://user-images.githubusercontent.com/9304640/66833028-bfca0780-ef63-11e9-926e-859c41e2f10c.jpg)

**Comment by kosvrouvas** [comment]
thanks @vagelisp! Μια χαρα τέλειο
