### ISSUE TITLE
Μεγάλο κενό μετά από συνδέσμους στο forum

### ISSUE THREAD

**Issue by dyrer** [wpgreece/wpgreece-theme#17]
Για παράδειγμα
https://wpgreece.org/forum/topic/%ce%b5%cf%80%ce%b9%ce%bb%ce%bf%ce%b3%ce%b5%cf%82-%ce%b3%ce%b9%ce%b1-%ce%bc%ce%b5%cf%84%ce%b1%cf%86%ce%bf%cf%81%ce%b9%ce%ba%ce%b1/

Υπάρχει μεγάλο κενό σε κάθε post που περιέχει σύνδεσμο από οτι εχω δει

**Comment by kosvrouvas** [comment]
Προσπαθέι να κάνει preview τη σελίδα οπως κάνει το link 2 μηνύματα παραπάνω, θα προσπαθήσω να δω γιατί δεν φορτώνει τελικά...

**Comment by kosvrouvas** [comment]
Κλείνω αυτό μιας και πλεον δεν έχουμε forum!
