### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by vbaimas** [wpgreece/wpgreece-theme#19]
Προτείνω να δημιουργηθεί ένα Code of Conduct το οποίο θα είναι open στο github λογιαριασμό της κοινότητας.
Η λογική πίσω από τον Κώδικα Συμπεριφοράς, έχει να κάνει με το πως θα συμπεριφέρονται συνολικά οι χρήστες της κοινότητας στα διάφορα κανάλια επικοινωνίας _(λχ Slack, Facebook κοκ)._ Ουσιαστικά, τι επιτρέπεται και τι όχι.

**Comment by kosvrouvas** [comment]
Άνοιξα αυτό: https://github.com/wpgreece/code-of-conduct/blob/master/readme.md
Και ο Τάκης έφτιαξε αυτό: https://wpgreece.org/%ce%ba%cf%8e%ce%b4%ce%b9%ce%ba%ce%b1%cf%82-%cf%83%cf%85%ce%bc%cf%80%ce%b5%cf%81%ce%b9%cf%86%ce%bf%cf%81%ce%ac%cf%82/

Το repo ίσως θέλει λίγο να γίνει πιο όμορφο
