### ISSUE TITLE
Navigation Menu/Η κοινότητα

### ISSUE THREAD

**Issue by vbaimas** [wpgreece/wpgreece-theme#2]
Στον μενού πλοήγησης η επιλογή : **"Η κοινότητα"** είναι προσβάσιμη-επισκέψιμη _(κάνουμε κλικ)_. Ίσως θα ήταν καλό να είχαμε μία υποσελίδα λχ **"Λίγα λόγια"** και σ' αυτήν να αναφέρουμε το περιεχόμενο.
Παρόμοιο "πρόβλημα" είχαμε και με τις υποσελίδες του WordCamp, το οποίο μας το επισημάναν και στην συνέχεια το διορθώσαμε, λχ "Χορηγοι" / "Οι Χορηγοί μας" / "Κάλεσμα για Χορηγούς" / "Media Sponsors".
Σύνοψη :  "Η Κοινότητα" / "Λίγα λόγια" / "Media Kit"

**Comment by ifrountas** [comment]
Και εδώ να το δεί ο @dyrer σαν πιο έμπειρος στα του content 🥇

**Comment by kosvrouvas** [comment]
Κλεινω γιατί μάλλον έχει διορθωθεί.
