### ISSUE TITLE
Author archive

### ISSUE THREAD

**Issue by vbaimas** [wpgreece/wpgreece-theme#3]
Όνομα συγγραφέα. Το μπλε χρώμα στο όνομα μου του author δίνει την αίσθηση ότι είναι ένας σύνδεσμος ο οποίος θα με κατευθύνει στο προφίλ του συγγραφέα, κάτι τέτοιο ισχύει μόνο στην περίπτωση του featured post των νέων αλλά όχι στα υπόλοιπα άρθρα _(δές αρχική)_

**Comment by ifrountas** [comment]
Εσύ @vbaimas  τι θα πρότεινες; Να γίνει παντού λινκ; Ή να αλλαχθεί το χρώμα;

**Comment by vbaimas** [comment]
Προτείνω να "κρατήσουμε" το Author archive και να έχει ο κάθε author το δικό του template. 
Λχ : "https://wpgreece.org/author/kouratoras/"

**Comment by ifrountas** [comment]
Άρα δηλαδή λες να γίνει σύνδεσμος προς την archive page όπου εμφανίζεται το όνομα του κάθε συντάκτη;

**Comment by vbaimas** [comment]
Ναι, αυτο προτείνω. Ας μπει ως request και το συζητάμε ξανά αν θέλετε.

**Comment by ifrountas** [comment]
Ωραία. Κάνω mention και τον @kosvrouvas να το δεί και τα λέμε όλοι μαζί και στο slack.

**Comment by kosvrouvas** [comment]
Χμ.. νομίζω πως ναι, θα ήταν ωραίο σε όλα τα σημεία να έχει το author page. Συνηθίζεται στα περισσότερα sites, από συνήθεια και μόνο ο άλλος έτσι σκέφτεται..

**Comment by kosvrouvas** [comment]
Καλησπέρα, το παραπάνω προστέθηκε!
