### ISSUE TITLE
Εικονίδια

### ISSUE THREAD

**Issue by vbaimas** [wpgreece/wpgreece-theme#4]
- Στην κατηγορία Εκδηλώσεις, έχουν προστεθεί τα εικονίδια των meetups και όχι των εκδηλώσεων.

![wpgreece-icons](https://cloud.githubusercontent.com/assets/5068068/22012409/90739604-dc9c-11e6-83f6-877c96257dad.png)

- Στην κατηγορία  : Θέματα (Themes), επίσης λείπουν τα εικονίδια που εκπροσωπούν την κατηγορία αυτή.

![wp-greece_icons-themes](https://cloud.githubusercontent.com/assets/5068068/22012634/c3cbf2d4-dc9d-11e6-8c7e-009cc9fb2e72.png)

 - Το ίδιο ισχύει για τις κατηγορίες :  "plugins", "security", "Frameworks", "Τεκμηριωση"

**Comment by ifrountas** [comment]
Βασίλη εδώ έχει γίνει το εξής, δεν έχουμε περάσει σε όλες τις καρηγορίες τα εικονίδια καθώς περιμένουμε απο @dyrer και την υπόλοιπη ομάδα να τις οριστικοποιήσουν.

**Comment by ifrountas** [comment]
Προς το παρόν πρόσθεσα κάποια, αλλά μένει να δούμε το παραπάνω.
