### ISSUE TITLE
Τελευταίες Δημοσιεύσεις στο forum

### ISSUE THREAD

**Issue by ArchimidisM** [wpgreece/wpgreece-theme#7]
Καλησπέρα, προτείνω στη σελίδα του forum  , έστω στη sidebar να δείχνει τις τελευταίες δημοσιεύσεις όπως και στο παλιό forum .

**Comment by kosvrouvas** [comment]
O @ifrountas νομιζω εχει κανει καποιες διορθώσεις πανω στο sidebar, μπορουμε να το προσθέσουμε;

**Comment by kosvrouvas** [comment]
Πλέον δεν έχουμε φόρουμ άρα το κλείνω αυτό
